/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ProductDBQuery;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author maine
 */
public class Page2 extends javax.swing.JFrame {

    ProductDBQuery productdb=new ProductDBQuery();
    
    public Page2() {
        
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
//        int i=0;
//        product1Label.setText((String)productdb.getProductName().get(i));
//        i++;
//        product2Label.setText((String)productdb.getProductName().get(i));
//        i++;
//        product3Label.setText((String)productdb.getProductName().get(i));
        ArrayList<JLabel> productButton=new ArrayList<>();
        productButton.add(product1Label);
        productButton.add(product2Label);
        productButton.add(product3Label);
        productButton.add(product4Label);
        productButton.add(product5Label);
        productButton.add(product6Label);
        productButton.add(product7Label);
        productButton.add(product8Label);
        productButton.add(product9Label);
        productButton.add(product10Label);

        for(int i=0; i<productButton.size(); i++)
           {
               productButton.get(i).setText((String)productdb.getProductName().get(i));
           }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        welcome_customerLabel = new javax.swing.JLabel();
        go_menuButton = new javax.swing.JButton();
        product1Label = new javax.swing.JLabel();
        product2Label = new javax.swing.JLabel();
        product3Label = new javax.swing.JLabel();
        product4Label = new javax.swing.JLabel();
        product5Label = new javax.swing.JLabel();
        product6Label = new javax.swing.JLabel();
        product7Label = new javax.swing.JLabel();
        product8Label = new javax.swing.JLabel();
        product9Label = new javax.swing.JLabel();
        product10Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcome_customerLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        welcome_customerLabel.setText("WELCOME CUSTOMER");

        go_menuButton.setText("Go menu");
        go_menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_menuButtonActionPerformed(evt);
            }
        });

        product1Label.setText("product1");

        product2Label.setText("product2");

        product3Label.setText("product3");

        product4Label.setText("product4");

        product5Label.setText("product5");

        product6Label.setText("product6");

        product7Label.setText("product7");

        product8Label.setText("product8");

        product9Label.setText("product9");

        product10Label.setText("product9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(welcome_customerLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(go_menuButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(product2Label)
                            .addComponent(product1Label)
                            .addComponent(product3Label)
                            .addComponent(product4Label)
                            .addComponent(product5Label)
                            .addComponent(product6Label)
                            .addComponent(product7Label)
                            .addComponent(product8Label)
                            .addComponent(product9Label)
                            .addComponent(product10Label))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcome_customerLabel)
                .addGap(42, 42, 42)
                .addComponent(product1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product3Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product4Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product5Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product6Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product7Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product8Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product9Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product10Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                .addComponent(go_menuButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void go_menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_menuButtonActionPerformed
        dispose();
      new Page1().setVisible(true);
    }//GEN-LAST:event_go_menuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton go_menuButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel product10Label;
    private javax.swing.JLabel product1Label;
    private javax.swing.JLabel product2Label;
    private javax.swing.JLabel product3Label;
    private javax.swing.JLabel product4Label;
    private javax.swing.JLabel product5Label;
    private javax.swing.JLabel product6Label;
    private javax.swing.JLabel product7Label;
    private javax.swing.JLabel product8Label;
    private javax.swing.JLabel product9Label;
    private javax.swing.JLabel welcome_customerLabel;
    // End of variables declaration//GEN-END:variables
}
