/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Dbutils;
import Controller.ProductDBQuery;
import Model.Order;
import Model.Product;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author maine
 */
public class Achat extends javax.swing.JFrame {

    //Fields
    private final ProductDBQuery productdb=new ProductDBQuery();
    private  ArrayList<Product> produit = new  ArrayList<Product>(); 
    private final ProductPage parentPage;
    private int here;
    private Order currentOrder;
    

    //Constructor
    public Achat(ProductPage p) {
        initComponents();
        parentPage=p;
    }
     
    
    //Méthode permettant d'afficher la page Achat sans créer une nouvelle JFrame à chaque fois
    //et qui affiche les informations du produit selectionné par le customer
    public void setAchat(int i, Order co) {
         
        this.currentOrder=co;
        this.here=i;
        
        try 
        {
       
            parentPage.setVisible(false);//On désaffiche la page parent, ie la Productpage
            
            //On établit la connection
            Connection conn= Dbutils.getDbConnection();
            produit=productdb.getProducts();
            
            //On affiche les informations relatives au produit choisi par le customer
            nameLabel.setText(produit.get(i).getProductName());
            priceLabel.setText(Double.toString(produit.get(i).getProductPrice())+"$");
            quantityLabel.setText(Integer.toString(produit.get(i).getProductStock())+"/100");
            //on clear le label si il n'y a pas de reductions
            if(produit.get(i).getProductQuantityDiscount()>0 && produit.get(i).getProductDiscount()>0)
             {
                 discountLabel.setText(produit.get(i).getProductQuantityDiscount()+"for £"+produit.get(i).getProductDiscount());
             }
             else 
             {
                 discountLabel.setText(" ");
             }
        
        }
        catch (SQLException ex) 
        {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        quantity1Label = new javax.swing.JLabel();
        quantityTextfield = new javax.swing.JTextField();
        discountLabel = new javax.swing.JLabel();
        invalaibleLabel = new javax.swing.JLabel();
        exitLabel2 = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();
        bucketLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(183, 183, 254));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 600));

        nameLabel.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("product_name");

        priceLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(255, 255, 255));
        priceLabel.setText("price");

        quantityLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        quantityLabel.setForeground(new java.awt.Color(255, 255, 255));
        quantityLabel.setText("quantity");

        quantity1Label.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        quantity1Label.setForeground(new java.awt.Color(255, 255, 255));
        quantity1Label.setText("QUANTITY");

        quantityTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quantityTextfieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantityTextfieldKeyTyped(evt);
            }
        });

        discountLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        discountLabel.setForeground(new java.awt.Color(255, 255, 255));

        exitLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/exiticon.png"))); // NOI18N
        exitLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabel2MouseClicked(evt);
            }
        });

        backLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/backIcon.png"))); // NOI18N
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });

        bucketLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/bucketIcon.png"))); // NOI18N
        bucketLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bucketLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(quantity1Label)
                        .addGap(50, 50, 50)
                        .addComponent(quantityTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(invalaibleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(discountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addComponent(bucketLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(backLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitLabel2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addComponent(quantityLabel))
                        .addGap(380, 380, 380))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(priceLabel)
                .addGap(190, 190, 190))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(backLabel)
                            .addComponent(exitLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(nameLabel)))
                .addGap(18, 18, 18)
                .addComponent(quantityLabel)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(priceLabel)
                        .addGap(18, 18, 18)
                        .addComponent(bucketLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(discountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantityTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantity1Label))
                        .addGap(27, 27, 27)
                        .addComponent(invalaibleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Méthode permettant d'effacer l'ancienne saisie de l'utilisateur
    public void clearQuantity()
    {
        quantityTextfield.setText("");   
    }
    
    private void quantityTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityTextfieldKeyTyped
        
        
    }//GEN-LAST:event_quantityTextfieldKeyTyped

    private void quantityTextfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityTextfieldKeyPressed
      invalaibleLabel.setText("");
        char car= evt.getKeyChar();
        //si c'est bien un nombre entrer
        if((car<'0' || car>'9' ) && quantityTextfield.getText().contains(".")
            && (car!=(char)KeyEvent.VK_BACK_SPACE))
        {
            invalaibleLabel.setText("");
            
        }
          //blindage si ce n'est pas un nombre
         else if((car<'0' ||car>'9')&&(car!='.')&&(car!=(char)KeyEvent.VK_BACK_SPACE))
    {
        invalaibleLabel.setText("please enter a number");
        invalaibleLabel.setForeground(Color.RED);
    }
    }//GEN-LAST:event_quantityTextfieldKeyPressed

    private void exitLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitLabel2MouseClicked

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        
        this.dispose();
        parentPage.setVisible(true);//On rend la Productpage visible
    }//GEN-LAST:event_backLabelMouseClicked

    private void bucketLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bucketLabelMouseClicked
       //We manage product stock
        int quantityInitial=produit.get(here).getProductStock();
        int quantityBuy=Integer.parseInt(quantityTextfield.getText());
        //dans le cas ou il y a un pb de stock
        if(quantityInitial<quantityBuy ||quantityBuy<=0)
            JOptionPane.showMessageDialog(null,"pb de stok");
        else
        {
            int quantityFinal=quantityInitial-quantityBuy;
            produit.get(here).setProductStock(quantityFinal);
            productdb.updateProduct(produit.get(here));
            
             //We actualize the current order
            int quanIni=currentOrder.getQuantity();
            double priceIni=currentOrder.getTotalPrice();

            currentOrder.setQuantity(quanIni+quantityBuy);

            int  n=quantityBuy;

            //si le produit a une reduction ...........
            if(produit.get(here).getProductQuantityDiscount()>0 && produit.get(here).getProductDiscount()>0)
            {

                currentOrder.setTotalPrice((n/produit.get(here).getProductQuantityDiscount()
                        *(produit.get(here).getProductDiscount())
                        +(n%produit.get(here).getProductQuantityDiscount())
                        *produit.get(here).getProductPrice())+priceIni);
            }
            else
            {
               currentOrder.setTotalPrice(priceIni+produit.get(here).getProductPrice()*quantityBuy);
            }

            //calcul du prix sans reduc
            double p=produit.get(here).getProductPrice()*quantityBuy;
            double newp=parentPage.getPsr()+p;
            parentPage.setPsr(newp);
            parentPage.addDeleteButton();


            //On ajoute le produit au panier
            parentPage.addToBucket(produit.get(here));
            parentPage.addQuantity(quantityBuy);

            //On affiche le panier en appelant la méthode updateTable
            parentPage.updateTable();

            //On met à jour le statut du panier
            parentPage.updateStatutBucket();

            //On met à jour le prix total
            parentPage.updateTotalPrice();

            //Back to Product page
            parentPage.getAchatPage().setVisible(false);
            parentPage.setVisible(true);
        }

    }//GEN-LAST:event_bucketLabelMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backLabel;
    private javax.swing.JLabel bucketLabel;
    private javax.swing.JLabel discountLabel;
    private javax.swing.JLabel exitLabel2;
    private javax.swing.JLabel invalaibleLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel quantity1Label;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JTextField quantityTextfield;
    // End of variables declaration//GEN-END:variables
}
